services:
  db:
    container_name: db
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
    ports:
      #- 127.0.0.1:${DB_PORT}:5432
      - ${DB_PORT}:5432
    networks:
      - spring-postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  spring-fullstack:
    container_name: spring-fullstack
    image: ghcr.io/ram0973/spring-fullstack:main
    environment:
      - APP_PROFILE=${APP_PROFILE}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - DB_HOST=db
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:${DB_PORT}/${DB_NAME}
    restart: no
    expose:
      - "8080"
    #ports:
    #  - "127.0.0.1:8080:8080"
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    depends_on:
      - postgres-service
    networks:
      - spring-postgres


volumes:
  postgresql-data:
networks:
  spring-postgres:
    driver: bridge
    #enable_ipv6: false
    #internal: true
