services:
  spring-fullstack-db:
    container_name: spring-fullstack-db
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 1s
      timeout: 5s
      retries: 10
    expose:
      - 5432
    networks:
      - spring-postgres
    volumes:
      - spring-fullstack-db-data:/var/lib/postgresql/data

  spring-fullstack:
    container_name: spring-fullstack
    image: ghcr.io/ram0973/spring-fullstack:main
    environment:
      - APP_PROFILE=${APP_PROFILE}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - DB_HOST=spring-fullstack-db
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
      #- SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${DB_NAME}
    restart: no
    #expose:
    #  - "8080"
    ports:
      - "8080:8080"
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    depends_on:
      spring-fullstack-db:
        condition: service_healthy
    networks:
      - spring-postgres


volumes:
  spring-fullstack-db-data:
networks:
  spring-postgres:
    driver: bridge
    #enable_ipv6: false
    #internal: true
