services:

  postgres-service-dev:
    profiles:
      - dev
    build:
      dockerfile: ./docker/postgresql/Dockerfile
    environment:
      - POSTGRES_DB=${DB_NAME-web}
      - POSTGRES_USER=${DB_USER-web}
      - POSTGRES_PASSWORD=${DB_PASSWORD-web}
    ports:
      - "${DB_PORT-5432}:5432"

  postgres-service-test:
    profiles:
      - test
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${TEST_DB_NAME-test}
      - POSTGRES_USER=${TEST_DB_USER-test}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD-test}
    ports:
      - "${TEST_DB_PORT-5434}:5432"

  mail-dev:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
