services:
  postgres-service:
    container_name: spring-docker
    image: 'postgres:16.6'
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    networks:
      - spring-postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data

  spring-boot-react-service:
    container_name: spring-boot
    image: ghcr.io/ram0973/spring-fullstack:main
    environment:
      - APP_PROFILE=$APP_PROFILE}
      - APP_ADMIN_EMAIL=${APP_ADMIN_EMAIL}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=${DB_PORT}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-service:${DB_PORT}/${DB_NAME}
    restart: no
    ports:
      - "8080:8080"
    #build:
    #  context: .
    #  dockerfile: ./Dockerfile
    depends_on:
      - postgres-service
    networks:
      - spring-postgres


volumes:
  postgresql-data:
networks:
  spring-postgres:
    driver: bridge
