app:
  admin:
    email: "gendalf-test-admin@white.com"
server:
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: web-test
  docker:
    compose:
      skip:
        in-tests: false
      profiles:
        active: test
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
