app:
  admin:
    email: "gendalf-dev-admin@white.com"
server:
  port: 8008
  servlet:
    session:
      timeout: 1800
spring:
  application:
    name: web-dev
  datasource:
    password: ${DB_PASSWORD:web}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:web}
    username: ${DB_USER:web}
  docker:
    compose:
      profiles:
        active: dev
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create-drop
