# AUTHENTICATION


### Register user
POST http://localhost:8000/api/v1/auth/register
Content-Type: application/json

{
  "email": "frodo@baggins.com",
  "password": "password"
}


### Login Admin
POST http://localhost:8000/api/v1/auth/login
Content-Type: application/json

{
  "email": "gendalf@white.com",
  "password": "password"
}


### Logout
POST http://localhost:8000/api/v1/auth/logout


### Me
GET http://localhost:8000/api/v1/auth/me
