### Get Users
GET http://localhost:8008/api/v1/users

### Get 1 User
GET http://localhost:8008/api/v1/users/1

### Create 1 User
POST http://localhost:8008/api/v1/users
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}

### Update 1 User
PATCH http://localhost:8008/api/v1/users/2
Content-Type: application/json

{
  "email": "test-changed@test.com",
  "password": "password-changed"
}

### Delete 1 User
DELETE http://localhost:8008/api/v1/users/2

