name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.6.0make bui
        with:
          distribution: 'liberica'
          java-version: '23'
      - run: make build
      - run: make test
