name: Build

on:
  - push
  - pull_request

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: self-hosted #ubuntu-22.04
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.6.0
        with:
          distribution: 'liberica'
          java-version: '23'
          cache: 'gradle'
      - run: chmod +x ./gradlew
        working-directory: .
      - run: make setup
      - run: make build
      - run: make test

  deploy:
    needs: build
    runs-on: self-hosted #ubuntu-22.04
    permissions:
      contents: read
      packages: write
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4.2.2
      #- uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3.3.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.6.1
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - uses: docker/build-push-action@v6.10.0
        with:
          context: .
          file: ./docker/spring/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          #cache-from: ram0973/spring-fullstack:latest
          #cache-to: type=inline
          #tags: ram0973/spring-fullstack:latest
#  prepare-environment:
#    runs-on: self-hosted
#    needs: deploy
#    steps:
#      - name: Stop and remove containers, networks
#        run: docker-compose down
#      - name: Remove unused data
#        run: docker system prune -a -f
#  run:
#    runs-on: self-hosted
#    needs: prepare-environment
#    env:
#      LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
#    steps:
#      - name: docker-compose
#        run: docker compose -f production.yml up -d
