name: Build

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/setup-java@v4.6.0
        with:
          distribution: 'liberica'
          java-version: '23'
          cache: 'gradle'
      - run: chmod +x ./gradlew
      - run: make setup
      - run: make build
      - run: make test

  deploy:
    needs: build
    runs-on: ubuntu-22.04
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/spring/Dockerfile
          push: true
          cache-from: ram0973/spring-fullstack:latest
          cache-to: type=inline
          tags: ram0973/spring-fullstack:latest
